name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        # run: action/checkout@v3 , run command is for echo "hhh" (running shell commands)
        uses: actions/checkout@v3
        #  with:
        #  github context supplies everything related to context
        # ${{ github.repository }}
        #   repository: ""
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
