name: Test & Deploy Project
# push is for running worflow when push happens, workflow_dispatch is for
# manual running of workflow.
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        # run: action/checkout@v3 , run command is for echo "hhh" (running shell commands)
        uses: actions/checkout@v3
        #  with:
        #  github context supplies everything related to context
        # ${{ github.repository }}
        #   repository: ""
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
  deploy:
    # deploy should run only after test job is successfull
    # we should give job name of dependent jobs, ex: [test, job2]
    needs: test # if above job fails, this job wont even start.
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        # run: action/checkout@v3 , run command is for echo "hhh" (running shell commands)
        uses: actions/checkout@v3
        #  with:
        #  github context supplies everything related to context
        # ${{ github.repository }}
        #   repository: ""
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying code"
